"""report-generation-migration

Revision ID: 127b84f1083c
Revises: c3303ff61f82
Create Date: 2024-03-25 03:07:48.519658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127b84f1083c'
down_revision: Union[str, None] = 'c3303ff61f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('for_nutrition_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('machineParam', sa.Integer(), nullable=True),
    sa.Column('demographicParam', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('record_owner_id', sa.Integer(), nullable=True),
    sa.Column('document_key', sa.String(), nullable=True),
    sa.Column('document_html_path', sa.String(), nullable=True),
    sa.Column('document_pdf_path', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_summary')
    op.drop_table('for_nutrition_report')
    # ### end Alembic commands ###
